<?php

declare(strict_types=1);
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>FourBag Network Administration</title>
<style>
:root{--bg:#efe7d8;--paper:#fffaf0;--ink:#191714;--muted:#71685e;--red:#a43a2d;--green:#315844;--line:#d8ccb9;--shadow:0 12px 34px rgba(40,30,20,.1)}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}.top{position:sticky;top:0;z-index:5;background:rgba(255,250,240,.94);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}.topin{max-width:1180px;margin:auto;padding:15px 20px;display:flex;justify-content:space-between;gap:14px;align-items:center}.brand{font:800 26px Georgia,serif}.brand small{display:block;font:800 9px Inter,sans-serif;text-transform:uppercase;letter-spacing:.16em;color:var(--red);margin-top:3px}.wrap{max-width:1180px;margin:auto;padding:22px 20px 60px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:15px}.card{grid-column:span 12;background:var(--paper);border:1px solid var(--line);border-radius:17px;box-shadow:var(--shadow);padding:18px}.s5{grid-column:span 5}.s7{grid-column:span 7}h1,h2{font-family:Georgia,serif;margin:0 0 12px}h1{font-size:28px}h2{font-size:21px}h3{font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:var(--green);margin:0 0 8px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.split{display:flex;justify-content:space-between;gap:12px;align-items:center}.btn{border:1px solid var(--line);border-radius:9px;background:#fffdf8;color:var(--ink);padding:9px 12px;font-weight:800;cursor:pointer}.btn.red{background:var(--red);border-color:var(--red);color:#fff}.btn.green{background:var(--green);border-color:var(--green);color:#fff}input,select{border:1px solid #cdbfa9;border-radius:9px;background:#fffdf8;padding:9px 10px;max-width:100%}.field{display:flex;flex-direction:column;gap:5px;margin-bottom:10px}.field label{font-size:11px;font-weight:800;color:var(--muted)}.muted{color:var(--muted)}.small{font-size:12px}.badge{display:inline-block;padding:5px 8px;border-radius:999px;background:#eee2cf;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.badge.green{background:#dfe9e1;color:#214331}.badge.red{background:#f2dedb;color:#7c291f}table{width:100%;border-collapse:collapse}th,td{padding:9px 8px;border-bottom:1px solid #e7ddcd;text-align:left;font-size:12px;vertical-align:middle}th{font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)}.table{overflow:auto}.notice{padding:12px;border:1px solid #dbc8ab;background:#efe3cf;border-radius:10px;font-size:12px;line-height:1.5}.error{background:#f4dfdc;border-color:#dfbdb7;color:#7b291f}.ok{background:#e3ebe4;border-color:#c6d7ca;color:#214331}.hidden{display:none!important}.empty{text-align:center;padding:24px;border:1px dashed #cdbfa9;border-radius:11px;color:var(--muted)}@media(max-width:800px){.s5,.s7{grid-column:span 12}.topin{align-items:flex-start;flex-direction:column}}
</style>
</head>
<body>
<header class="top"><div class="topin"><div class="brand">FOURBAG<small>Network Administration</small></div><div class="row" id="authBar"><input id="email" type="email" placeholder="Admin email"><input id="password" type="password" placeholder="Password"><button class="btn green" id="login">Sign In</button></div></div></header>
<main class="wrap"><div id="message" style="margin-bottom:12px"></div><div id="signedOut" class="card"><h3>Administrator Access</h3><h1>Manage FourBag venue accounts.</h1><p class="small muted">Create the first administrator with <code>scripts/create-admin.php</code>, then use this page to assign venue owners, managers, and scorekeepers.</p></div><div id="adminApp" class="grid hidden"><section class="card"><div class="split"><div><h3>Network</h3><h1>Venue Access</h1></div><button class="btn" id="refresh">Refresh</button></div><div class="table"><table><thead><tr><th>Venue</th><th>Location</th><th>Status</th><th>Members</th><th>Active Seasons</th><th>Equipment</th></tr></thead><tbody id="venues"></tbody></table></div></section><section class="card s5"><h3>Assign Access</h3><h2>Add / Update Venue Role</h2><div class="field"><label>Venue</label><select id="venueSelect"></select></div><div class="field"><label>Existing FourBag Account Email</label><input id="memberEmail" type="email" placeholder="manager@example.com"></div><div class="field"><label>Role</label><select id="role"><option value="owner">Owner</option><option value="manager">Manager</option><option value="scorekeeper">Scorekeeper</option></select></div><button class="btn green" id="assign">Assign Role</button><div class="notice" style="margin-top:12px">The person must already have a FourBag user account. Owners and managers can run league operations. Scorekeepers can record scores only.</div></section><section class="card s7"><div class="split"><div><h3>Selected Venue</h3><h2>Members</h2></div><button class="btn" id="loadMembers">Load Members</button></div><div class="table"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Status</th><th></th></tr></thead><tbody id="members"></tbody></table></div></section></div></main>
<script>
const $=id=>document.getElementById(id);let currentUser=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tell(text,type='ok'){$('message').innerHTML=text?`<div class="notice ${type}">${esc(text)}</div>`:''}
async function api(action,{method='GET',body=null,query={}}={}){const qs=new URLSearchParams({action,...query});const headers={'Accept':'application/json'};if(body)headers['Content-Type']='application/json';const r=await fetch(`api.php?${qs}`,{method,headers,credentials:'same-origin',body:body?JSON.stringify(body):null});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j.data}
async function authState(){try{const d=await api('auth.me');currentUser=d.user;if(currentUser&&currentUser.system_role==='admin'){showApp();await loadVenues()}else if(currentUser){throw new Error('Administrator access required.')}else{showSignedOut()}}catch(e){showSignedOut();tell(e.message,'error')}}
function showSignedOut(){$('adminApp').classList.add('hidden');$('signedOut').classList.remove('hidden')}
function showApp(){$('adminApp').classList.remove('hidden');$('signedOut').classList.add('hidden');$('authBar').innerHTML=`<span class="badge green">admin</span><strong>${esc(currentUser.display_name)}</strong><button class="btn" id="logout">Sign Out</button>`;$('logout').onclick=logout}
async function login(){try{const d=await api('auth.login',{method:'POST',body:{email:$('email').value,password:$('password').value}});currentUser=d.user;if(currentUser.system_role!=='admin')throw new Error('Administrator access required.');showApp();tell('Signed in.');await loadVenues()}catch(e){tell(e.message,'error')}}
async function logout(){await api('auth.logout',{method:'POST'});location.reload()}
async function loadVenues(){try{const rows=await api('admin.venues');$('venues').innerHTML=rows.length?rows.map(v=>`<tr><td><strong>${esc(v.name)}</strong></td><td>${esc([v.city,v.state].filter(Boolean).join(', '))}</td><td><span class="badge ${v.status==='active'?'green':''}">${esc(v.status)}</span></td><td>${Number(v.active_members)}</td><td>${Number(v.active_seasons)}</td><td>${Number(v.deployed_kits)}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No venues yet.</div></td></tr>';$('venueSelect').innerHTML=rows.map(v=>`<option value="${Number(v.id)}">${esc(v.name)}</option>`).join('');await loadMembers();tell('')}catch(e){tell(e.message,'error')}}
async function loadMembers(){const venueId=Number($('venueSelect').value||0);if(!venueId){$('members').innerHTML='<tr><td colspan="5"><div class="empty">Choose a venue.</div></td></tr>';return}try{const rows=await api('venue.members',{query:{venue_id:venueId}});$('members').innerHTML=rows.length?rows.map(m=>`<tr><td><strong>${esc(m.display_name)}</strong></td><td>${esc(m.email)}</td><td>${esc(m.role)}</td><td>${esc(m.status)}</td><td>${m.status==='active'?`<button class="btn red" onclick="revoke(${venueId},${Number(m.user_id)})">Revoke</button>`:''}</td></tr>`).join(''):'<tr><td colspan="5"><div class="empty">No assigned venue users.</div></td></tr>'}catch(e){tell(e.message,'error')}}
async function assign(){try{await api('venue.member.assign',{method:'POST',body:{venue_id:Number($('venueSelect').value),email:$('memberEmail').value.trim(),role:$('role').value}});$('memberEmail').value='';tell('Venue role assigned.');await loadVenues()}catch(e){tell(e.message,'error')}}
async function revoke(venueId,userId){if(!confirm('Revoke this venue role?'))return;try{await api('venue.member.revoke',{method:'POST',body:{venue_id:venueId,user_id:userId}});tell('Venue role revoked.');await loadVenues()}catch(e){tell(e.message,'error')}}
$('login').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('assign').onclick=assign;$('refresh').onclick=loadVenues;$('loadMembers').onclick=loadMembers;$('venueSelect').onchange=loadMembers;authState();
</script>
</body>
</html>
