<?php

declare(strict_types=1);
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>FourBag Host Fee Administration</title>
<style>
:root{--bg:#efe7d8;--paper:#fffaf0;--ink:#191714;--muted:#71685e;--red:#a43a2d;--green:#315844;--line:#d8ccb9;--shadow:0 12px 34px rgba(40,30,20,.1)}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}.top{position:sticky;top:0;z-index:4;background:rgba(255,250,240,.94);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}.topin{max-width:1180px;margin:auto;padding:15px 20px;display:flex;justify-content:space-between;gap:14px;align-items:center}.brand{font:800 26px Georgia,serif}.brand small{display:block;font:800 9px Inter,sans-serif;text-transform:uppercase;letter-spacing:.16em;color:var(--red);margin-top:3px}.wrap{max-width:1180px;margin:auto;padding:24px 20px 60px}.grid{display:grid;grid-template-columns:repeat(12,1fr);gap:15px}.card{grid-column:span 12;background:var(--paper);border:1px solid var(--line);border-radius:17px;box-shadow:var(--shadow);padding:18px}.s5{grid-column:span 5}.s7{grid-column:span 7}h1,h2{font-family:Georgia,serif;margin:0 0 12px}h1{font-size:30px}h2{font-size:21px}h3{font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:var(--green);margin:0 0 8px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.split{display:flex;justify-content:space-between;gap:12px;align-items:center}.btn{border:1px solid var(--line);border-radius:9px;background:#fffdf8;color:var(--ink);padding:9px 12px;font-weight:800;cursor:pointer;text-decoration:none}.btn.green{background:var(--green);border-color:var(--green);color:#fff}.btn.red{background:var(--red);border-color:var(--red);color:#fff}input,select,textarea{border:1px solid #cdbfa9;border-radius:9px;background:#fffdf8;padding:9px 10px;max-width:100%;font:inherit}.field{display:flex;flex-direction:column;gap:5px;margin-bottom:10px}.field label{font-size:11px;font-weight:800;color:var(--muted)}.authInput{width:190px}.muted{color:var(--muted)}.small{font-size:12px}.badge{display:inline-block;padding:5px 8px;border-radius:999px;background:#eee2cf;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.badge.green{background:#dfe9e1;color:#214331}.badge.red{background:#f2dedb;color:#7c291f}.notice{padding:12px;border:1px solid #dbc8ab;background:#efe3cf;border-radius:10px;font-size:12px;line-height:1.5}.error{background:#f4dfdc;border-color:#dfbdb7;color:#7b291f}.ok{background:#e3ebe4;border-color:#c6d7ca;color:#214331}.empty{text-align:center;padding:26px;border:1px dashed #cdbfa9;border-radius:11px;color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{padding:10px 8px;border-bottom:1px solid #e7ddcd;text-align:left;font-size:12px;vertical-align:middle}th{font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)}.table{overflow:auto}.hidden{display:none!important}@media(max-width:820px){.s5,.s7{grid-column:span 12}.topin,.split{align-items:flex-start;flex-direction:column}.authInput{width:100%}.wrap{padding-left:12px;padding-right:12px}}
</style>
</head>
<body>
<header class="top"><div class="topin"><div class="brand">FOURBAG<small>Host Fee Administration</small></div><div class="row"><a class="btn" href="admin.php">Network Admin</a><a class="btn" href="billing.php">Venue Billing</a><div class="row" id="authBar"><input class="authInput" id="email" type="email" placeholder="Admin email"><input class="authInput" id="password" type="password" placeholder="Password"><button class="btn green" id="login">Sign In</button></div></div></div></header>
<main class="wrap"><div id="message" style="margin-bottom:12px"></div><section id="signedOut" class="card"><h3>FourBag Administrator</h3><h1>Create and review league host fees.</h1><p class="muted">Only FourBag network administrators can issue host-fee invoices.</p></section><div id="app" class="grid hidden"><section class="card s5"><h3>New Invoice</h3><h2>League host fee</h2><div class="field"><label>League Season</label><select id="seasonSelect"></select></div><div class="field"><label>Amount (USD)</label><input id="amount" inputmode="decimal" value="500.00"></div><div class="field"><label>Due Date</label><input id="dueDate" type="date"></div><div class="field"><label>Description</label><textarea id="description" rows="3">FourBag league host fee</textarea></div><button class="btn green" id="createInvoice">Create Host-Fee Invoice</button><div class="notice" style="margin-top:12px">A season can have only one active host-fee invoice. Paid or open invoices block duplicate billing.</div></section><section class="card s7"><div class="split"><div><h3 id="venueLabel">Selected Venue</h3><h2>Invoice History</h2></div><button class="btn" id="refresh">Refresh</button></div><div class="table"><table><thead><tr><th>#</th><th>Season</th><th>Amount</th><th>Due</th><th>Status</th><th>Paid</th></tr></thead><tbody id="invoiceBody"></tbody></table></div></section></div></main>
<script>
const $=id=>document.getElementById(id);let currentUser=null,currentVenueId=0;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(c,cur='USD')=>new Intl.NumberFormat(undefined,{style:'currency',currency:String(cur||'USD').toUpperCase()}).format(Number(c||0)/100);
function tell(text,type='ok'){$('message').innerHTML=text?`<div class="notice ${type}">${esc(text)}</div>`:''}
async function api(action,{method='GET',body=null,query={}}={}){const qs=new URLSearchParams({action,...query});const headers={'Accept':'application/json'};if(body)headers['Content-Type']='application/json';const r=await fetch(`api.php?${qs}`,{method,headers,credentials:'same-origin',body:body?JSON.stringify(body):null});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j.data}
async function authState(){try{const d=await api('auth.me');currentUser=d.user;if(currentUser&&currentUser.system_role==='admin'){showApp();await loadSeasons()}else if(currentUser){throw new Error('Administrator access required.')}else showSignedOut()}catch(e){showSignedOut();tell(e.message,'error')}}
function showSignedOut(){$('app').classList.add('hidden');$('signedOut').classList.remove('hidden')}
function showApp(){$('app').classList.remove('hidden');$('signedOut').classList.add('hidden');$('authBar').innerHTML=`<span class="badge green">admin</span><strong>${esc(currentUser.display_name)}</strong><button class="btn" id="logout">Sign Out</button>`;$('logout').onclick=logout}
async function login(){try{const d=await api('auth.login',{method:'POST',body:{email:$('email').value,password:$('password').value}});currentUser=d.user;if(currentUser.system_role!=='admin')throw new Error('Administrator access required.');showApp();tell('Signed in.');await loadSeasons()}catch(e){tell(e.message,'error')}}
async function logout(){await api('auth.logout',{method:'POST'});location.reload()}
async function loadSeasons(){try{const rows=await api('seasons');$('seasonSelect').innerHTML=rows.map(s=>`<option value="${Number(s.id)}">${esc(s.venue_name)} — ${esc(s.name)}</option>`).join('');if(rows.length)await loadInvoices();else $('invoiceBody').innerHTML='<tr><td colspan="6"><div class="empty">No league seasons found.</div></td></tr>'}catch(e){tell(e.message,'error')}}
async function resolveVenue(){const seasonId=Number($('seasonSelect').value||0);if(!seasonId)throw new Error('Choose a league season.');const ops=await api('operations',{query:{season_id:seasonId}});currentVenueId=Number(ops.season.venue_id||0);$('venueLabel').textContent=ops.season.name?`${ops.season.name} • Venue ${currentVenueId}`:`Venue ${currentVenueId}`;return currentVenueId}
async function loadInvoices(){try{const venueId=await resolveVenue();const rows=await api('venue.invoices',{query:{venue_id:venueId}});$('invoiceBody').innerHTML=rows.length?rows.map(r=>`<tr><td>#${Number(r.id)}</td><td>${esc(r.season_name||'—')}</td><td><strong>${money(r.amount_cents,r.currency)}</strong></td><td>${esc(r.due_date||'—')}</td><td><span class="badge ${r.status==='paid'?'green':r.status==='open'?'red':''}">${esc(r.status)}</span></td><td>${esc(r.paid_at||'—')}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No host-fee invoices for this venue.</div></td></tr>';tell('')}catch(e){tell(e.message,'error')}}
async function createInvoice(){const amount=Number($('amount').value);if(!Number.isFinite(amount)||amount<1){tell('Enter a valid host fee amount.','error');return}try{const d=await api('admin.host_fee.create',{method:'POST',body:{season_id:Number($('seasonSelect').value),amount_cents:Math.round(amount*100),due_date:$('dueDate').value||null,description:$('description').value.trim()||null}});tell(`Invoice #${d.id} created for ${money(d.amount_cents,d.currency)}.`);await loadInvoices()}catch(e){tell(e.message,'error')}}
$('login').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('createInvoice').onclick=createInvoice;$('refresh').onclick=loadInvoices;$('seasonSelect').onchange=loadInvoices;authState();
</script>
</body>
</html>
