<?php

declare(strict_types=1);
?><!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>FourBag Player History Administration</title>
<style>
:root{--bg:#efe7d8;--paper:#fffaf0;--ink:#191714;--muted:#71685e;--red:#a43a2d;--green:#315844;--line:#d8ccb9;--shadow:0 12px 34px rgba(40,30,20,.1)}
*{box-sizing:border-box}body{margin:0;background:var(--bg);color:var(--ink);font-family:Inter,system-ui,-apple-system,Segoe UI,sans-serif}.top{position:sticky;top:0;z-index:4;background:rgba(255,250,240,.95);backdrop-filter:blur(12px);border-bottom:1px solid var(--line)}.topin{max-width:1180px;margin:auto;padding:15px 20px;display:flex;justify-content:space-between;gap:14px;align-items:center}.brand{font:800 26px Georgia,serif}.brand small{display:block;font:800 9px Inter,sans-serif;text-transform:uppercase;letter-spacing:.16em;color:var(--red);margin-top:3px}.wrap{max-width:1180px;margin:auto;padding:24px 20px 60px}.card{background:var(--paper);border:1px solid var(--line);border-radius:17px;box-shadow:var(--shadow);padding:18px;margin-bottom:15px}h1,h2{font-family:Georgia,serif;margin:0 0 12px}h1{font-size:30px}h2{font-size:21px}h3{font-size:11px;text-transform:uppercase;letter-spacing:.11em;color:var(--green);margin:0 0 8px}.row{display:flex;gap:8px;align-items:center;flex-wrap:wrap}.split{display:flex;justify-content:space-between;gap:12px;align-items:center}.btn{border:1px solid var(--line);border-radius:9px;background:#fffdf8;color:var(--ink);padding:9px 12px;font-weight:800;cursor:pointer;text-decoration:none}.btn.green{background:var(--green);border-color:var(--green);color:#fff}.btn.red{background:var(--red);border-color:var(--red);color:#fff}input{border:1px solid #cdbfa9;border-radius:9px;background:#fffdf8;padding:9px 10px;max-width:100%}.authInput{width:190px}.muted{color:var(--muted)}.small{font-size:12px}.badge{display:inline-block;padding:5px 8px;border-radius:999px;background:#eee2cf;font-size:10px;font-weight:900;text-transform:uppercase;letter-spacing:.05em}.badge.green{background:#dfe9e1;color:#214331}.badge.red{background:#f2dedb;color:#7c291f}.notice{padding:12px;border:1px solid #dbc8ab;background:#efe3cf;border-radius:10px;font-size:12px;line-height:1.5}.error{background:#f4dfdc;border-color:#dfbdb7;color:#7b291f}.ok{background:#e3ebe4;border-color:#c6d7ca;color:#214331}.hidden{display:none!important}.empty{text-align:center;padding:24px;border:1px dashed #cdbfa9;border-radius:11px;color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{padding:10px 8px;border-bottom:1px solid #e7ddcd;text-align:left;font-size:12px;vertical-align:middle}th{font-size:10px;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)}.table{overflow:auto}@media(max-width:760px){.topin,.split{align-items:flex-start;flex-direction:column}.authInput{width:100%}.wrap{padding-left:12px;padding-right:12px}}
</style>
</head>
<body>
<header class="top"><div class="topin"><div class="brand">FOURBAG<small>Player History Administration</small></div><div class="row"><a class="btn" href="admin.php">Network Admin</a><div class="row" id="authBar"><input class="authInput" id="email" type="email" placeholder="Admin email"><input class="authInput" id="password" type="password" placeholder="Password"><button class="btn green" id="login">Sign In</button></div></div></div></header>
<main class="wrap"><div id="message" style="margin-bottom:12px"></div><section id="signedOut" class="card"><h3>FourBag Administrator</h3><h1>Link verified legacy player history.</h1><p class="muted">Player history is not automatically claimed by an account created after the history already exists. An administrator can link it after verifying the player’s identity.</p></section><div id="app" class="hidden"><section class="card"><div class="split"><div><h3>Unlinked Players</h3><h1>History awaiting an account link</h1><p class="small muted">Only matching player/account email addresses can be linked. Verify identity outside this screen before completing a legacy link.</p></div><button class="btn" id="refresh">Refresh</button></div><div class="table"><table><thead><tr><th>Player</th><th>Email</th><th>Registrations</th><th>First</th><th>Matching Account</th><th></th></tr></thead><tbody id="players"></tbody></table></div></section></div></main>
<script>
const $=id=>document.getElementById(id);let currentUser=null;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tell(text,type='ok'){$('message').innerHTML=text?`<div class="notice ${type}">${esc(text)}</div>`:''}
async function api(action,{method='GET',body=null,query={}}={}){const qs=new URLSearchParams({action,...query});const headers={'Accept':'application/json'};if(body)headers['Content-Type']='application/json';const r=await fetch(`api.php?${qs}`,{method,headers,credentials:'same-origin',body:body?JSON.stringify(body):null});const j=await r.json();if(!j.ok)throw new Error(j.error||'Request failed');return j.data}
function showSignedOut(){$('app').classList.add('hidden');$('signedOut').classList.remove('hidden')}
function showApp(){$('app').classList.remove('hidden');$('signedOut').classList.add('hidden');$('authBar').innerHTML=`<span class="badge green">admin</span><strong>${esc(currentUser.display_name)}</strong><button class="btn" id="logout">Sign Out</button>`;$('logout').onclick=logout}
async function authState(){try{const d=await api('auth.me');currentUser=d.user;if(currentUser&&currentUser.system_role==='admin'){showApp();await loadPlayers()}else if(currentUser){throw new Error('Administrator access required.')}else showSignedOut()}catch(e){showSignedOut();tell(e.message,'error')}}
async function login(){try{const d=await api('auth.login',{method:'POST',body:{email:$('email').value,password:$('password').value}});currentUser=d.user;if(currentUser.system_role!=='admin')throw new Error('Administrator access required.');showApp();tell('Signed in.');await loadPlayers()}catch(e){tell(e.message,'error')}}
async function logout(){await api('auth.logout',{method:'POST'});location.reload()}
async function loadPlayers(){try{const rows=await api('admin.players.unlinked');$('players').innerHTML=rows.length?rows.map(p=>`<tr><td><strong>${esc(p.name)}</strong><div class="small muted">Player #${Number(p.player_id)}</div></td><td>${esc(p.email)}</td><td>${Number(p.registration_count)}</td><td>${esc(p.first_registered_at||'—')}</td><td>${p.account_id?`<strong>${esc(p.account_name)}</strong><div class="small muted">${esc(p.account_status)}</div>`:'<span class="badge">No account</span>'}</td><td>${p.account_id&&p.account_status==='active'?`<button class="btn green" onclick="linkHistory('${esc(p.email)}')">Link Verified History</button>`:''}</td></tr>`).join(''):'<tr><td colspan="6"><div class="empty">No unlinked player history.</div></td></tr>';tell('')}catch(e){tell(e.message,'error')}}
async function linkHistory(email){if(!confirm(`Link verified FourBag history to the account for ${email}?`))return;try{await api('admin.player.link',{method:'POST',body:{player_email:email,user_email:email}});tell('Player history linked.');await loadPlayers()}catch(e){tell(e.message,'error')}}
$('login').onclick=login;$('password').addEventListener('keydown',e=>{if(e.key==='Enter')login()});$('refresh').onclick=loadPlayers;authState();
</script>
</body>
</html>
